apps/accounting/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.accounting.views import *

urlpatterns = [
    path('', login_required(Home.as_view()), name='home'),
    path('get_purchases_list/', login_required(get_purchases_list), name='get_purchases_list'),
    path('get_dict_purchases/', login_required(get_dict_purchases), name='get_dict_purchases'),
    path('get_purchases_by_date/', login_required(get_purchases_by_date), name='get_purchases_by_date'),
    path('new_opening_balance/', login_required(new_opening_balance), name='new_opening_balance'),
    path('get_purchases_pay/', login_required(get_purchases_pay), name='get_purchases_pay'),
    path('new_payment_purchase/', login_required(new_payment_purchase), name='new_payment_purchase'),

    # cash
    path('get_cash_control_list/', login_required(get_cash_control_list), name='get_cash_control_list'),
    path('open_cash/', login_required(open_cash), name='open_cash'),
    path('close_cash/', login_required(close_cash), name='close_cash'),
    path('get_initial_balance/', login_required(get_initial_balance), name='get_initial_balance'),
    path('get_cash_date/', login_required(get_cash_date), name='get_cash_date'),
    path('update_description_cash/', login_required(update_description_cash), name='update_description_cash'),


    # accounts
    path('get_account_list/', login_required(get_account_list), name='get_account_list'),
    path('new_account/', login_required(new_account), name='new_account'),
    path('new_entity/', login_required(new_entity), name='new_entity'),
    path('get_entity/', login_required(get_entity), name='get_entity'),
    path('update_entity/', login_required(update_entity), name='update_entity'),

    # banks
    path('get_bank_control_list/', login_required(get_bank_control_list), name='get_bank_control_list'),
    path('update_description_and_date_cash_bank/', login_required(update_description_and_date_cash_bank), name='update_description_and_date_cash_bank'),
    path('get_modal_edit/', login_required(get_modal_edit), name='get_modal_edit'),

    # transactions
    path('new_bank_transaction/', login_required(new_bank_transaction), name='new_bank_transaction'),
    path('new_cash_disbursement/', login_required(new_cash_disbursement), name='new_cash_disbursement'),
    path('new_transfer_bank/', login_required(new_transfer_bank), name='new_transfer_bank'),
    path('get_cash_by_subsidiary/', login_required(get_cash_by_subsidiary), name='get_cash_by_subsidiary'),
    path('new_cash_transfer_to_cash/', login_required(new_cash_transfer_to_cash), name='new_cash_transfer_to_cash'),
    path('get_confirm_cash_to_cash_transfer/', login_required(get_confirm_cash_to_cash_transfer), name='get_confirm_cash_to_cash_transfer'),
    path('new_cash_to_bank/', login_required(new_cash_to_bank), name='new_cash_to_bank'),
    path('accept_cash_to_cash_transfer/', login_required(accept_cash_to_cash_transfer), name='accept_cash_to_cash_transfer'),
    path('desist_cash_to_cash_transfer/', login_required(desist_cash_to_cash_transfer), name='desist_cash_to_cash_transfer'),
    path('new_bank_to_cash_transfer/', login_required(new_bank_to_cash_transfer), name='new_bank_to_cash_transfer'),

    # reportes
    path('get_cash_report/', login_required(get_cash_report), name='get_cash_report'),
    path('get_cash_by_dates/', login_required(get_cash_by_dates), name='get_cash_by_dates'),
    path('update_transaction_date_in_cash_flow/', login_required(update_transaction_date_in_cash_flow), name='update_transaction_date_in_cash_flow'),

    # graphics
    path('get_graphic_cash_set_vs_purchase/', login_required(get_graphic_cash_set_vs_purchase), name='get_graphic_cash_set_vs_purchase'),

    # Salary
    path('get_report_employees_salary/', login_required(get_report_employees_salary), name='get_report_employees_salary'),
    path('get_salary_pay/', login_required(get_salary_pay), name='get_salary_pay'),
    path('new_payment_salary/', login_required(new_payment_salary), name='new_payment_salary'),

    # Tributes
    path('report_tributary/', login_required(report_tributary), name='report_tributary'),
    path('save_register_tributary/', login_required(save_register_tributary), name='save_register_tributary'),
]

dglp/urls.py
# import autocomplete_light
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

from apps.hrm.views import Home
from apps.users.views import Login, logoutUser

# autocomplete_light.autodiscover()
# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dishes/', include(('apps.dishes.urls', 'dishes'))),
    path('api/v1/', include(('apps.apidishes.urls', 'apidishes'))),
    path('vetstore/', include(('apps.vetstore.urls', 'vetstore'))),
    path('hrm/', include(('apps.hrm.urls', 'hrm'))),
    path('comercial/', include(('apps.comercial.urls', 'comercial'))),
    path('sales/', include(('apps.sales.urls', 'sales'))),
    path('buys/', include(('apps.buys.urls', 'buys'))),
    path('accounting/', include(('apps.accounting.urls', 'accounting'))),

    path('', login_required(Home.as_view()), name='dashboard'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(logoutUser), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += [
#         static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
#         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     ]

apps/accounting/models.py
from django.db import models
from django.contrib.auth.models import User
import decimal

# Create your models here.
from django.db.models import Sum, Count


class TransactionAccount(models.Model):
    DOCUMENT_TYPE_ATTACHED_CHOICES = (
        ('F', 'Factura'), ('B', 'Boleta'), ('T', 'Ticket'), ('V', 'Vale'),
        ('O', 'Otro'))
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    amount = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    product = models.ForeignKey('sales.Product', on_delete=models.SET_NULL, null=True, blank=True)
    order_detail = models.ForeignKey('sales.OrderDetail', on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    transaction_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    description = models.CharField('Descripcion', max_length=100, null=True, blank=True)
    serial = models.CharField('Serie', max_length=5, null=True, blank=True)
    n_receipt = models.IntegerField('Numero de Comprobante', default=0, null=True, blank=True)
    document_type_attached = models.CharField('Tipo documento', max_length=1, choices=DOCUMENT_TYPE_ATTACHED_CHOICES,
                                              default='O', )

    def __str__(self):
        return str(self.pk)


class AccountingAccount(models.Model):
    code = models.CharField('Codigo', max_length=45, null=True, blank=True)
    description = models.CharField('Descripcion', max_length=200, null=True, blank=True)
    parent_code = models.CharField('Codigo Padre', max_length=45, null=True, blank=True)

    def __str__(self):
        return str(self.code)


class LedgerEntry(models.Model):
    TYPE_CHOICES = (('D', 'Debito'), ('C', 'Credito'),)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    amount = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    product = models.ForeignKey('sales.Product', on_delete=models.SET_NULL, null=True, blank=True)
    order_detail = models.ForeignKey('sales.OrderDetail', on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES, default='D', )

    account = models.ForeignKey(AccountingAccount, on_delete=models.SET_NULL, null=True, blank=True)
    transaction = models.ForeignKey(TransactionAccount, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return str(self.pk)


class Cash(models.Model):
    CURRENCY_TYPE_CHOICES = (('S', 'Soles'), ('E', 'Euros'), ('D', 'Dolares'),)
    name = models.CharField('Nombre', max_length=100, unique=True, null=True, blank=True)
    subsidiary = models.ForeignKey('hrm.Subsidiary', on_delete=models.SET_NULL, null=True, blank=True)
    account_number = models.CharField(max_length=14, null=True, blank=True)
    accounting_account = models.ForeignKey(AccountingAccount, on_delete=models.SET_NULL, null=True, blank=True)
    initial = models.DecimalField(max_digits=10, decimal_places=2, default='0', )
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    currency_type = models.CharField('Tipo de moneda', max_length=1, choices=CURRENCY_TYPE_CHOICES, default='S', )

    def __str__(self):
        return str(self.name)

    def current_balance(self):
        inputs = 0
        outputs = 0
        opening = 0
        cash_flow_set = CashFlow.objects.filter(cash_id=self.pk)
        initial = self.initial

        if cash_flow_set:
            last_cash_flow_obj = cash_flow_set.last()
            inputs_bank_flow_set = cash_flow_set.filter(type='D').values('type').annotate(totals=Sum('total'))
            outputs_bank_flow_set = cash_flow_set.filter(type='R').values('type').annotate(totals=Sum('total'))

            cash_flow_set = cash_flow_set.filter(transaction_date__date=last_cash_flow_obj.transaction_date.date())
            inputs_cash_flow_set = cash_flow_set.filter(type='E').values('transaction_date__date').annotate(
                totals=Sum('total'))
            outputs_cash_flow_set = cash_flow_set.filter(type='S').values('transaction_date__date').annotate(
                totals=Sum('total'))
            if self.accounting_account.code.startswith('1041'):
                if last_cash_flow_obj.type == 'D':
                    if inputs_bank_flow_set:
                        inputs = inputs_bank_flow_set[0].get('totals')
                    opening = initial
                    if outputs_bank_flow_set:
                        outputs = outputs_bank_flow_set[0].get('totals')
                elif last_cash_flow_obj.type == 'R':
                    if outputs_bank_flow_set:
                        outputs = outputs_bank_flow_set[0].get('totals')
                    opening = initial
                    if inputs_bank_flow_set:
                        inputs = inputs_bank_flow_set[0].get('totals')

            elif self.accounting_account.code.startswith('101'):

                if last_cash_flow_obj.type == 'A':
                    opening = last_cash_flow_obj.total
                elif last_cash_flow_obj.type == 'C':
                    opening = last_cash_flow_obj.total
                elif last_cash_flow_obj.type == 'E':

                    opening_cash_flow_set = cash_flow_set.filter(type='A')
                    if opening_cash_flow_set:
                        opening = opening_cash_flow_set.last().total

                    inputs = inputs_cash_flow_set[0].get('totals')
                    if outputs_cash_flow_set:
                        outputs = outputs_cash_flow_set[0].get('totals')

                elif last_cash_flow_obj.type == 'S':

                    opening_cash_flow_set = cash_flow_set.filter(type='A')
                    if opening_cash_flow_set:
                        opening = opening_cash_flow_set.last().total

                    outputs = outputs_cash_flow_set[0].get('totals')
                    if inputs_cash_flow_set:
                        inputs = inputs_cash_flow_set[0].get('totals')

        else:
            opening = self.initial

        return opening + inputs - outputs


class CashTransfer(models.Model):
    STATUS_CHOICES = (('P', 'Pendiente'), ('A', 'Aceptado'), ('C', 'Cancelado'),)
    id = models.AutoField(primary_key=True)
    status = models.CharField('Tipo de Transferencia', max_length=1, choices=STATUS_CHOICES, default='P', )

    def __str__(self):
        return str(self.id)

    def get_origin(self):
        origin_set = CashTransferRoute.objects.filter(cash_transfer__id=self.id, type='O')
        origin = None
        if origin_set.count() > 0:
            origin = origin_set.last().cash
        return origin

    def get_destiny(self):
        destiny_set = CashTransferRoute.objects.filter(cash_transfer__id=self.id, type='D')
        destiny = None
        if destiny_set.count() > 0:
            destiny = destiny_set.last().cash
        return destiny

    def the_one_that_requests(self):
        action_set = CashTransferAction.objects.filter(cash_transfer__id=self.id, operation='E')
        cash_transfer_action = None
        if action_set.count() > 0:
            cash_transfer_action = action_set.last()
        return cash_transfer_action

    def the_one_that_approves(self):
        action_set = CashTransferAction.objects.filter(cash_transfer__id=self.id, operation='A')
        cash_transfer_action = None
        if action_set.count() > 0:
            cash_transfer_action = action_set.last()
        return cash_transfer_action

    def the_one_that_cancel(self):
        action_set = CashTransferAction.objects.filter(cash_transfer__id=self.id, operation='C')
        cash_transfer_action = None
        if action_set.count() > 0:
            cash_transfer_action = action_set.last()
        return cash_transfer_action

    def get_amount(self):
        cash_origin_obj = self.get_origin()
        amount = 0
        if cash_origin_obj:
            cash_flow_set = cash_origin_obj.cashflow_set.filter(cash_transfer__id=self.id)
            if cash_flow_set:
                amount = cash_flow_set.first().total
        return amount

    class Meta:
        verbose_name = 'Transferencia de caja'
        verbose_name_plural = 'Transferencias de cajas'


class CashFlow(models.Model):
    DOCUMENT_TYPE_ATTACHED_CHOICES = (
        ('F', 'Factura'), ('B', 'Boleta'), ('T', 'Ticket'), ('V', 'Vale'), ('O', 'Otro'))
    OPERATION_TYPE_CHOICES = (
    ('1', 'Deposito'), ('2', 'Pago electronico'), ('3', 'Compra electronica'), ('4', 'Extraccion bancaria'),
    ('5', 'Transferencia bancaria'), ('6', 'Transferencia de Caja a Caja'), ('7', 'Transferencia de Caja a banco'),
    ('0', 'Ninguno'))
    TYPE_CHOICES = (
    ('A', 'Apertura'), ('C', 'Cierre'), ('E', 'Entrada'), ('S', 'Salida'), ('D', 'Deposito'), ('R', 'Retiro'),
    ('T', 'Transferencia'),)
    transaction_date = models.DateTimeField(auto_now_add=False, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    description = models.CharField('Descripcion', max_length=200, null=True, blank=True)
    serial = models.CharField('Serie', max_length=5, null=True, blank=True)
    n_receipt = models.IntegerField('Numero de Comprobante', default=0, null=True, blank=True)
    document_type_attached = models.CharField('Tipo documento', max_length=1, choices=DOCUMENT_TYPE_ATTACHED_CHOICES,
                                              default='O', )
    type = models.CharField('Tipo de transaccion', max_length=1, choices=TYPE_CHOICES, default='E', )
    subtotal = models.DecimalField('subtotal', max_digits=30, decimal_places=15, default=0)
    total = models.DecimalField('total', max_digits=30, decimal_places=15, default=0)

templates/accounting/banking_list.html
{% extends 'home.html' %}

{% block title %}
    coronasoft.dev | Control de caja
{% endblock title %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <form class="form-inline" id="search-form" method="POST">
                    {% csrf_token %}
                    <label class="my-1 mr-2" for="id-cash">Banco</label>
                    <select class="custom-select my-1 mr-sm-2" id="id-cash" name="cash" required>
                        <option value="" disabled selected>SELECCIONE...</option>

                        {% for c in only_bank_set %}
                            <option value="{{ c.pk }}">{{ c.name }}</option>
                        {% endfor %}

                    </select>

                    <label class="my-1 mr-2" for="id-start-date">Fecha Inicial</label>
                    <input type="date" class="form-control my-1 mr-sm-2" id="id-start-date" name="start-date"
                           value="{{ formatdate }}">

                    <label class="my-1 mr-2" for="id-end-date">Fecha final</label>
                    <input type="date" class="form-control my-1 mr-sm-2" id="id-end-date" name="end-date"
                           value="{{ formatdate }}">

                    <button type="submit" class="btn btn-primary my-1">
                        <i class="fas fa-search-dollar" id="btn-search"></i> Buscar
                    </button>

                </form>

            </div>
            <div class="col-sm-6">
                <button type="button" class="btn btn-danger m-1" data-toggle="modal" data-target="#modal-transaction">
                    <i class="fas fa-comments-dollar"></i> Movimientos
                </button>

                <button type="button" class="btn btn-success m-1" data-toggle="modal" data-target="#modal-transfer">
                    <i class="fas fa-exchange-alt"></i> Transferencias
                </button>

                <button type="button" class="btn btn-success m-1" data-toggle="modal"
                        data-target="#modal-transfer-to-cash" disabled>
                    <i class="fas fa-random"></i> Transferencias a caja
                </button>

            </div>
        </div>


        <div id="account-grid-list"></div>

    </div>

    <div class="modal" id="modal-transaction" tabindex="-1" role="dialog">

        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-header pb-2 pt-2">
                    <h4 class="modal-title mb-3 mt-3">Movimientos bancarios</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% include "accounting/new_banking_transactions.html" with formatdate=formatdate %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="modal-transfer" tabindex="-1" role="dialog">

        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <div class="modal-header pb-2 pt-2">
                    <h4 class="modal-title mb-3 mt-3">Transferencias bancarias</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% include "accounting/new_banking_transfers.html" with formatdate=formatdate %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="modal-transfer-to-cash" tabindex="-1" role="dialog">

        <div class="modal-dialog modal-dialog-centered modal-xl">
            <div class="modal-content">
                <div class="modal-header pb-2 pt-2">
                    <h4 class="modal-title mb-3 mt-3">Transferencias a cajas</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% include "accounting/new_bank_to_cash.html" with formatdate=formatdate %}
                </div>
            </div>
        </div>
    </div>

    <div class="modal" id="exampleModalCenter" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-dialog-centered  modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenterTitle">Editar elemento seleccionado:</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-edit"> </div>

            </div>
        </div>
    </div>

{% endblock body %}

{% block extrajs %}
    <script type="text/javascript">

        $("#id-transfer-bank-destiny").chained("#id-transfer-subsidiary-destiny");

        $('#search-form').submit(function (event) {
            event.preventDefault();

            let _data = new FormData($('#search-form').get(0));

            $("#btn-search").attr("disabled", "true");


            $.ajax({
                url: '/accounting/get_bank_control_list/',
                type: "POST",
                data: _data,
                cache: false,
                processData: false,
                contentType: false,
                success: function (response, textStatus, xhr) {
                    if (xhr.status === 200) {
                        $('#account-grid-list').html(response.grid);
                        toastr.info(response['message'], '¡Bien hecho!');
                    }
                },
                error: function (jqXhr, textStatus, xhr) {
                    if (jqXhr.status === 500) {
                        toastr.error(jqXhr.responseJSON.error, '¡Inconcebible!');
                        $('#account-grid-list').html('<div class="alert alert-info alert-dismissible fade show mt-3" role="alert">\n' +
                            '        <strong>Atencion!</strong> Tu debes ingresar una fecha primero.\n' +
                            '        <button type="button" class="close" data-dismiss="alert" aria-label="Close">\n' +
                            '            <span aria-hidden="true">×</span>\n' +
                            '        </button>\n' +
                            '    </div>');
                    }
                }
            });
            $("#btn-search").removeAttr("disabled", "false");
            $('#search-form').modal('hide');

        });

        $('#id-start-date').change(function () {
            $('#id-end-date').val($(this).val());
        });

        $('#id-bank-cash').change(function () {
            $('#id-bank-account').val($(this).find('option:selected').attr('account-number'));
            $('#id-bank-current-balance').val($(this).find('option:selected').attr('current-balance'));
        });


        $('#new-bank-transaction-form').submit(function (event) {
            event.preventDefault();
            let data = new FormData($('#new-bank-transaction-form').get(0));

            $('#btn-bank-operation-save').attr("disabled", "true");

            $.ajax({
                url: '/accounting/new_bank_transaction/',
                type: "POST",
                data: data,
                cache: false,
                processData: false,
                contentType: false,
                success: function (response, textStatus, xhr) {
                    if (xhr.status == 200) {
                        // $('#product-detail-grid').html(response.grid);
                        $('#modal-transaction').modal('hide');
                        toastr.success(response['message'], '¡Bien hecho!');
                    }
                },
                error: function (jqXhr, textStatus, xhr) {
                    if (jqXhr.status == 500) {
                        toastr.error(jqXhr.responseJSON.error, '¡Inconcebible!');
                    }
                }
            });
            $('#btn-bank-operation-save').removeAttr("disabled", "false");
        });


        $('#new-transfer-form').submit(function (event) {
            event.preventDefault();
            let data = new FormData($('#new-transfer-form').get(0));

            $('#btn-transfer-save').attr("disabled", "true");

            $.ajax({
                url: '/accounting/new_transfer_bank/',
                type: "POST",
                data: data,
                cache: false,
                processData: false,
                contentType: false,
                success: function (response, textStatus, xhr) {
                    if (xhr.status == 200) {
                        // $('#product-detail-grid').html(response.grid);
                        $('#modal-transfer').modal('hide');
                        toastr.success(response['message'], '¡Bien hecho!');
                    }
                },
                error: function (jqXhr, textStatus, xhr) {
                    if (jqXhr.status == 500) {
                        toastr.error(jqXhr.responseJSON.error, '¡Inconcebible!');
                    }
                }
            });
            $('#btn-transfer-save').removeAttr("disabled", "false");
        });

        $('#id-transfer-bank-origin').change(function () {
            $('#id-transfer-bank-balance').val($(this).find('option:selected').attr('current-balance'));
        });


        $('#new-btc-form').submit(function (event) {
            event.preventDefault();
            let data = new FormData($('#new-btc-form').get(0));

            $('#btn-btc-cash-save').attr("disabled", "true");

            $.ajax({
                url: '/accounting/new_bank_to_cash_transfer/',
                type: "POST",
                data: data,
                cache: false,
                processData: false,
                contentType: false,
                success: function (response, textStatus, xhr) {
                    if (xhr.status == 200) {
                        // $('#product-detail-grid').html(response.grid);
                        $('#modal-transfer-to-cash').modal('hide');
                        toastr.success(response['message'], '¡Bien hecho!');
                    }
                },
                error: function (jqXhr, textStatus, xhr) {
                    if (jqXhr.status == 500) {
                        toastr.error(jqXhr.responseJSON.error, '¡Inconcebible!');
                    }
                }
            });
            $('#btn-btc-cash-save').removeAttr("disabled", "false");
        });


    </script>
{% endblock extrajs %}

templates/accounting/cash_form.html
<form class="needs-validation" id="cash-form" method="POST">

    {% csrf_token %}

    <div class="mb-3">
        <label for="id-select-cash">Caja</label>

        <select class="custom-select my-1 mr-sm-2" id="id-select-cash" name="select-cash" required>
            <option value="" disabled selected>SELECCIONE...</option>

            {% for c in only_cash_set %}
                <option value="{{ c.pk }}">{{ c.name }}</option>
            {% endfor %}

        </select>


        <div class="invalid-feedback">
            Valid account name is required.
        </div>
    </div>


    <div class="mb-3">
        <label for="account-value">Saldo inicial/día anterior</label>
        <input type="text" class="form-control" id="cash-amount" name="cash-amount" readonly>
        <div class="invalid-feedback">
            Valid value name is required.
        </div>
    </div>

    <hr class="mb-4">

    <div class="mb-3">
        <label for="account-created">Fecha de registro</label>
        <input type="date" class="form-control" id="cash-date" name="cash-date" placeholder="" value="{{ formatdate }}"
               required="">
        <div class="invalid-feedback">
            Valid date is required.
        </div>
    </div>


    <hr class="mb-4">
    <button class="btn btn-primary btn-lg btn-block" type="submit" id="btn-save">Aperturar</button>
</form>

templates/accounting/modal_edit_bank.html
<div class="form-row">
    <div class="col-md-3 mb-3">
        <input type="hidden" id="id_cash_flow" value="{{ c.id }}">
        <label for="validationTooltip01">Editar Fecha seleccionada:</label>
        <input type="date" class="form-control" id="id_date" placeholder="First name"
               value="{{ c.transaction_date|date:"Y-m-d" }}" required>
        <div class="valid-tooltip">
            Looks good!
        </div>
    </div>
    <div class="col-md-9 mb-3">
        <label for="validationTooltip02">Editar Descripción selecccionada:</label>
        <input type="text" class="form-control" id="id_description" placeholder="Last name"
               value="{{ c.description }}" required>
        <div class="valid-tooltip">
            Looks good!
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
    <button type="button" class="btn btn-primary"
            onclick="cashDescriptionEditBank()">Guardar cambios
    </button>
</div>