apps/hrm/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.hrm.views import *

urlpatterns = [
    path('', login_required(Home.as_view()), name='home'),
    path('employee_list/', login_required(EmployeeList.as_view()), name='employee_list'),
    path('json_employee_create/', login_required(JsonEmployeeCreate.as_view()), name='json_employee_create'),
    path('json_employee_list/', login_required(JsonEmployeeList.as_view()), name='json_employee_list'),
    path('json_employee_edit/<int:pk>/',
         login_required(JsonEmployeeUpdate.as_view()), name='json_employee_edit'),
    path('get_worker_designation/', get_worker_designation, name='get_worker_designation'),
    path('create_worker/', create_worker, name='create_worker'),
    path('get_establishment_code/', get_establishment_code, name='get_establishment_code'),
    path('get_worker_establishment/', get_worker_establishment, name='get_worker_establishment'),
    path('update_worker_establishment/', update_worker_establishment, name='update_worker_establishment'),
    path('get_worker_user/', get_worker_user, name='get_worker_user'),
    path('update_worker_user/', update_worker_user, name='update_worker_user'),
    path('edit_worker_designation/', edit_worker_designation, name='edit_worker_designation'),
    path('update_worker/', login_required(update_worker), name='update_worker'),
]

dglp/urls.py
# import autocomplete_light
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

from apps.hrm.views import Home
from apps.users.views import Login, logoutUser

# autocomplete_light.autodiscover()
# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dishes/', include(('apps.dishes.urls', 'dishes'))),
    path('api/v1/', include(('apps.apidishes.urls', 'apidishes'))),
    path('vetstore/', include(('apps.vetstore.urls', 'vetstore'))),
    path('hrm/', include(('apps.hrm.urls', 'hrm'))),
    path('comercial/', include(('apps.comercial.urls', 'comercial'))),
    path('sales/', include(('apps.sales.urls', 'sales'))),
    path('buys/', include(('apps.buys.urls', 'buys'))),
    path('accounting/', include(('apps.accounting.urls', 'accounting'))),

    path('', login_required(Home.as_view()), name='dashboard'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(logoutUser), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += [
#         static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
#         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     ]

apps/buys/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

from apps.hrm.models import Subsidiary, District, DocumentType
from apps.sales.models import Unit, Product, Supplier, SubsidiaryStore, LoanPayment
from apps.comercial.models import Truck
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust


class Purchase(models.Model):
    STATUS_CHOICES = (('S', 'SIN ALMACEN'), ('A', 'EN ALMACEN'), ('N', 'ANULADO'),)
    TYPE_CHOICES = (('T', 'TICKET'), ('B', 'BOLETA'), ('F', 'FACTURA'),)
    id = models.AutoField(primary_key=True)
    supplier = models.ForeignKey(Supplier, verbose_name='Proveedor', on_delete=models.CASCADE, null=True, blank=True)
    purchase_date = models.DateField('Fecha compra', null=True, blank=True)
    bill_number = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='S')
    truck = models.ForeignKey(Truck, on_delete=models.SET_NULL, null=True, blank=True)
    type_bill = models.CharField('Tipo de comprobante', max_length=1, choices=TYPE_CHOICES, default='T')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Compra'
        verbose_name_plural = 'Compras'

    def total(self):
        response = 0
        purchase_detail_set = PurchaseDetail.objects.filter(purchase__id=self.id)
        for pd in purchase_detail_set:
            response = response + (pd.quantity * pd.price_unit)
        return response


class PurchaseDetail(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, null=True, blank=True)
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.DecimalField('Cantidad comprada', max_digits=10, decimal_places=2, default=0)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True, blank=True)
    price_unit = models.DecimalField('Precio unitario', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

    def multiplicate(self):
        return self.quantity * self.price_unit

    class Meta:
        verbose_name = 'Detalle compra'
        verbose_name_plural = 'Detalles de compra'


class Requirement_buys(models.Model):
    STATUS_CHOICES = (('1', 'PENDIENTE'), ('2', 'APROBADO'), ('3', 'ANULADO'), ('4', 'FINALIZADO'),)
    STATUS_CHOICES_PAYMENT = (('1', 'PENDIENTE'), ('2', 'PAGADO'), ('3', 'ANULADO'),)
    TYPE_CHOICES = (('M', 'MERCADERIA'), ('I', 'INSUMO'),)
    id = models.AutoField(primary_key=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='1', )
    status_pay = models.CharField('Estado de Pago', max_length=1, choices=STATUS_CHOICES_PAYMENT, default='1', )
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES, default='M', )
    creation_date = models.DateField('Fecha de solicitud', null=True, blank=True)
    number_scop = models.CharField('Numero de scop', max_length=45, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    approval_date = models.DateField('Fecha de aprobación', null=True, blank=True)
    invoice = models.CharField('Factura', max_length=45, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    def sum_loan_payment_pen(self):
        response = 0
        loan_payment_set = LoanPayment.objects.filter(requirement_detail_buys__requirement_buys=self.id)
        if loan_payment_set.exists():
            for lp in loan_payment_set:
                if lp.get_cash_flow().cash.currency_type == 'S':
                    response = response + lp.price
        return response

    def sum_loan_payment_dollar(self):
        response = 0
        loan_payment_set = LoanPayment.objects.filter(requirement_detail_buys__requirement_buys=self.id)
        if loan_payment_set.exists():
            for lp in loan_payment_set:
                if lp.get_cash_flow().cash.currency_type == 'D':
                    response = response + lp.price
        return response

    def debt(self):
        debt = 0
        price_total = 0
        debt_total = RequirementDetail_buys.objects.filter(requirement_buys=self.id).values('amount')
        for p in debt_total:
            price_total = price_total + p['amount']
        debt = self.sum_loan_payment_dollar() - price_total
        return debt

    class Meta:
        verbose_name = 'Requerimiento'
        verbose_name_plural = 'Requerimientos'


class RequirementDetail_buys(models.Model):
    COIN_CHOICES = ((1, 'DOLAR(ES)'), (2, 'SOLE(S)'),)
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    requirement_buys = models.ForeignKey('Requirement_buys', on_delete=models.CASCADE, related_name='requirements_buys',
                                         null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    amount = models.DecimalField('Importe', max_digits=30, decimal_places=15, default=0)
    price_pen = models.DecimalField('Precio soles', max_digits=30, decimal_places=15, default=0)
    amount_pen = models.DecimalField('Importe soles', max_digits=30, decimal_places=15, default=0)
    coin = models.IntegerField('Moneda', choices=COIN_CHOICES, default=1, )
    change_coin = models.DecimalField('Cambio', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

    def multiplicate(self):
        return self.quantity * self.price

    class Meta:
        verbose_name = 'Detalle requerimiento'
        verbose_name_plural = 'Detalles de requerimiento'


class RequirementBuysProgramming(models.Model):
    STATUS_CHOICES = (('P', 'PROGRAMADO'), ('F', 'FINALIZADO'),)
    id = models.AutoField(primary_key=True)
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE, related_name='truck', null=True, blank=True)
    date_programming = models.DateField('Fecha de solicitud', null=True, blank=True)
    number_scop = models.CharField('Numero de scop', max_length=45, null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='P', )
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='rpsubsidiary')

    def __str__(self):
        return str(self.id)

    def calculate_total_programming_expenses_price(self):
        # try:
        response = ProgrammingExpense.objects.filter(
            requirementBuysProgramming__id=self.id).values(
            'requirementBuysProgramming').annotate(totals=Sum('price'))
        if (response.exists()):
            return response[0].get('totals')
        else:
            return 0

    # except ProgrammingExpense.DoesNotExist:
    #     return 0

    class Meta:
        verbose_name = 'Programacion de Requerimiento GLP'
        verbose_name_plural = 'Programaciones de Requerimiento GLP'


class Programminginvoice(models.Model):
    STATUS_CHOICES = (('P', 'PENDIENTE'), ('R', 'REGISTRADO'),)
    id = models.AutoField(primary_key=True)
    requirementBuysProgramming = models.ForeignKey(RequirementBuysProgramming, on_delete=models.SET_NULL, null=True,
                                                   blank=True)
    requirement_buys = models.ForeignKey(Requirement_buys, on_delete=models.SET_NULL, null=True, blank=True)
    date_arrive = models.DateField('Fecha de entrada', null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='P', )
    guide = models.CharField('Numero Guia', max_length=45, null=True, blank=True)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    subsidiary_store_destiny = models.ForeignKey(SubsidiaryStore, on_delete=models.SET_NULL, null=True, blank=True,
                                                 related_name='destinies')
    subsidiary_store_origin = models.ForeignKey(SubsidiaryStore, on_delete=models.SET_NULL, null=True, blank=True,
                                                related_name='origins')

    def __str__(self):
        return str(self.id)

    def calculate_total_quantity(self):
        response = Programminginvoice.objects.filter(requirement_buys_id=self.requirement_buys.id).values(
            'requirement_buys').annotate(totals=Sum('quantity'))
        # return response.count
        if response:
            return response[0].get('totals')
        else:
            return 0

    def calculate_total_programming_quantity(self):
        response = Programminginvoice.objects.filter(
            requirementBuysProgramming_id=self.requirementBuysProgramming.id).values(
            'requirementBuysProgramming').annotate(totals=Sum('quantity'))
        # return response.count
        if response:
            return response[0].get('totals')
        else:
            return 0

    class Meta:
        verbose_name = 'Factura GLP'
        verbose_name_plural = 'Facturas GLP'


class ProgrammingExpense(models.Model):
    STATUS_CHOICES = (('P', 'PENDIENTE'), ('R', 'REGISTRADO'),)
    TYPE_CHOICES = (

templates/hrm/employee_grid_list.html
{% if employees %}

    <!-- <h2 class='mb-3'>Basic example</h2> -->

    <div class="card">

        <div class="card-header">
            <h5 class="card-title">Lista de trabajadores</h5>
            <h6 class="card-subtitle text-muted">Highly flexible tool that many advanced features to any HTML
                table.</h6>
        </div>

        <div class="card-body">

            <div class="table-responsive dataTables_wrapper ">

                <table id="employee-data-grid" class="table table-bordered" cellspacing="0" width="100%">
                    <thead>
                    <tr class="text-center">
                        <th>#</th>
                        <th class="th-sm">Empleado (TD)</th>
                        <th class="th-sm">Sede</th>
                        <th class="th-sm">Usuario</th>
                        <th class="th-sm">Vinculo con la empresa</th>
                        <th class="th-sm">Creado</th>
                        <th class="th-sm">Accion</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for employee in employees %}
                        <tr class="text-center">
                            <!-- <td>{{ dish.id }}</td> -->
                            <td></td>
                            <td>
                                <address class="text-left">
                                    <strong>{{ employee.paternal_last_name }} {{ employee.maternal_last_name|slice:":1" }}, {{ employee.names }}</strong><br>
                                    Nacionalidad, <i>{{ employee.document_issuing_country }}</i><br>
                                    Tipo de documento, {{ employee.document_type|lower|capfirst }}<br>
                                    Numero de documento, {{ employee.document_number }}<br>
                                </address>
                            </td>
                            <td class="align-middle">{{ employee.worker_set.last.establishment_set.last.subsidiary.name|default:"-" }}</td>
                            <td class="align-middle">{{ employee.worker_set.last.user.username|default:"-" }}</td>
                            <td class="align-middle">
                                {% if employee.worker_set.count > 0 %}
                                    <address class="text-left">
                                    <strong>Trabajador</strong><br>
                                    Ocupación, <i>{{ employee.worker_set.last.occupation_private_sector.name }}</i><br>
                                    Tipo de trabajador, <i>{{ employee.worker_set.last.get_worker_type.description }}</i><br>
                                    Régimen de Aseguramiento de Salud, <i>{{ employee.worker_set.last.get_health_insurance_regime.description }}</i><br>
                                    Régimen pensionario, <i>{{ employee.worker_set.last.get_pensioner_regime.description }}</i><br>
                                    </address>
                                {% else %}-{% endif %}</td>
                            <td class="align-middle">{{ employee.created_at|date:"SHORT_DATE_FORMAT" }} {{ employee.created_at|time:"H:i" }}</td>

                            <td>

                                <!-- Example single danger button -->
                                <div class="btn-group">
                                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                        Action
                                    </button>

                                    <div class="dropdown-menu bg-info text-white">

                                        <a class="dropdown-item" style="cursor: pointer;"
                                           onclick="showModalEdition('{% url 'hrm:json_employee_edit' employee.id %}')">
                                            <i class="fas fa-edit"></i> Editar
                                        </a>
                                        {% if employee.worker_set.count == 0 %}
                                            <a class="dropdown-item worker-designation" style="cursor: pointer;" pk="{{ employee.id }}">
                                                <i class="fas fa-sync-alt"></i> Datos del trabajador
                                            </a>
                                        {% else %}
                                            <a class="dropdown-item worker-change-designation" style="cursor: pointer;"
                                               pk="{{ employee.worker_set.last.id }}">
                                                <i class="fas fa-sync-alt"></i> Modificar datos del trabajador
                                            </a>
                                            <a class="dropdown-item worker-change-establishment" style="cursor: pointer;"
                                               pk="{{ employee.worker_set.last.id }}">
                                                <i class="fas fa-sync-alt"></i> Modificar de sede
                                            </a>
                                            <a class="dropdown-item worker-change-user" style="cursor: pointer;"
                                               pk="{{ employee.worker_set.last.id }}">
                                                <i class="fas fa-sync-alt"></i> Modificar de usuario
                                            </a>
                                        {% endif %}
                                        <a class="dropdown-item staff-in-training-designation" style="cursor: pointer;" pk="{{ employee.id }}">
                                            <i class="fas fa-sync-alt"></i> Modalidad Personal en formación
                                        </a>

                                        <a class="dropdown-item third-party-personnel-designation" style="cursor: pointer;"
                                           pk="{{ employee.id }}">
                                            <i class="fas fa-sync-alt"></i> Modalidad Personal de tercero
                                        </a>

                                    </div>
                                </div>


                            </td>

                        </tr>
                    {% endfor %}


                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <th>#</th>
                        <th class="th-sm">Empleado (TD)</th>
                        <th class="th-sm">Sede</th>
                        <th class="th-sm">Usuario</th>
                        <th class="th-sm">Vinculo con la empresa</th>
                        <th class="th-sm">Creado</th>
                        <th class="th-sm">Accion</th>
                    </tr>
                    </tfoot>
                </table>

            </div>

        </div>

        <!-- Card -->
    </div>



{% else %}
    <h1>No existen trabajadores registrados</h1>
{% endif %}

templates/hrm/employee_list.html
{% extends 'home.html' %}

{% block title %}
coronasoft.dev | Datos personales del trabajador
{% endblock title %}

{% block body %}


<!-- Content -->
<div class="container-fluid">

    <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
    <button type="button" onclick="showModalCreation('{% url 'hrm:json_employee_create' %}')" class="btn btn-outline-info mb-5">
        <i class="fas fa-user-plus"></i> &nbsp; NUEVO TRABAJADOR
    </button>

    <div id="employee-grid-list" >{% include "hrm/employee_grid_list.html" %}</div>

</div>


<div class="modal fade bd-example-modal-lg" id="creation" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
<div class="modal fade" id="edition" tabindex="-1" role="dialog" aria-labelledby="ModalHelpTitle" aria-hidden="true"></div>
<div class="modal fade" id="get-worker-designation" tabindex="-1" role="dialog" aria-labelledby="ModalHelpTitle" aria-hidden="true"></div>
<div class="modal fade" id="get-worker-establishment" tabindex="-1" role="dialog" aria-labelledby="ModalHelpTitle" aria-hidden="true"></div>
<div class="modal fade" id="get-worker-user" tabindex="-1" role="dialog" aria-labelledby="ModalHelpTitle" aria-hidden="true"></div>



{% endblock body %}


{% block extrajs %}
<script type="text/javascript">

    var $ = jQuery.noConflict();

    $('#employee-data-grid').dataTable({
        columnDefs: [{
            orderable: false,
            className: 'select-checkbox',
            targets: 0
        }],
        select: {
            style: 'os',
            selector: 'td:first-child'
        }
    });
    $(document).on('click', '.worker-designation', function () {
        var search = $(this).attr('pk');
        $.ajax({
            url: '/hrm/get_worker_designation/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                console.log(response);
                if(response.success){
                    $('#get-worker-designation').html(response.form);
                    $('#get-worker-designation').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });
    $(document).on('click', '.worker-change-designation', function () {
        var search = $(this).attr('pk');
        $.ajax({
            url: '/hrm/edit_worker_designation/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                console.log(response);
                if(response.success){
                    $('#get-worker-designation').html(response.form);
                    $('#get-worker-designation').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });
    $(document).on('click', '.worker-change-establishment', function () {
        let search = $(this).attr('pk');
        $.ajax({
            url: '/hrm/get_worker_establishment/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                console.log(response);
                if(response.success){
                    $('#get-worker-establishment').html(response.form);
                    $('#get-worker-establishment').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });
    $(document).on('click', '.worker-change-user', function () {
        let search = $(this).attr('pk');
        $.ajax({
            url: '/hrm/get_worker_user/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                console.log(response);
                if(response.success){
                    $('#get-worker-user').html(response.form);
                    $('#get-worker-user').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });

    $('.staff-in-training-designation').on('click', function () {
        var search = $(this).attr('pk');
        $.ajax({
            url: '/sales/get_kardex_by_product/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                console.log(response);
                if(response.success){
                    $('#show-kardex').html(response.form);
                    $('#show-kardex').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });

    $('.third-party-personnel-designation').on('click', function () {
        var search = $(this).attr('pk');
        $.ajax({
            url: '/sales/set_product_detail/',
            dataType: 'json',
            type: 'GET',
            data: {'pk': search},
            success: function (response) {
                if(response.success){
                    console.log(response.serialized_data);
                    $('#get-worker-designation').html(response.form);
                    $('#get-worker-designation').modal('show');
                }
            },
            fail: function (response) {
                console.log(response);
            }
        });
    });

    function refreshTable() {
        $('#employee-data-grid').DataTable().draw();
    }

    function showModalDelete(url) {
        $('#delete').load(url, function () {
            $(this).modal('show');
        });
    };

    function showModalEdition(url) {
        $('#edition').load(url, function () {
            $(this).modal('show');
        });
    };

    function showModalCreation(url) {
        $('#creation').load(url, function () {
            $(this).modal('show');
        });
    };


</script>
{% endblock extrajs %}

templates/hrm/worker_establishment.html
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">

    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title">Actualizar sede del trabajador</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <form id="worker-establishment-form" action="" method="POST" class="was-validated">
            {% csrf_token %}
            <input type="hidden" id="id_worker" name="worker" value="{{ worker.id }}">

            <div class="modal-body">


                <table class="table">
                    <tr>
                        <td>Sede actual:</td>
                        <td>
                            {{ worker.establishment_set.last.subsidiary.name }}
                        </td>
                    </tr>
                    <tr>
                        <td>Nueva Sede:</td>
                        <td>
                            {{ form.subsidiary }}
                        </td>
                    </tr>
                </table>


            </div><!-- modal-body -->


            <div class="modal-footer">&nbsp;
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                &nbsp;
                <button id="btn-worker-establishment-submit" type="submit" class="btn btn-primary">Guardar</button>


            </div>

        </form>

    </div>
</div>

<script type="text/javascript">

    $('#id_subsidiary').attr('required','required');

    $('#worker-establishment-form').submit(function (event) {
        event.preventDefault();

        var data = new FormData($('#worker-establishment-form').get(0));

        $("#btn-worker-establishment-submit").attr("disabled");

        $.ajax({
            url: "/hrm/update_worker_establishment/",
            type: "POST",
            data: data,
            cache: false, //If set to false, it will force requested pages not to be cached by the browser.
            processData: false, // Important!, it prevent jQuery form transforming the data into a query string
            contentType: false, //Es imperativo que establezca la opción contentType en false, forzando a jQuery a no agregar un encabezado Content-Type
            success: function (response, textStatus, xhr) {
                //Recibe un json serializado
                console.log(response);

                if (xhr.status == 200) {
                    toastr.success('Guardado con exito.', '¡Bien hecho!');

                    $.ajax({
                        url: '{% url 'hrm:json_employee_list' %}',
                        async: true,
                        dataType: 'json',
                        type: 'GET',
                        // data: {'search': search},
                        success: function (response) {
                            $("#employee-grid-list").html(response.result);
                            refreshTable();
                            setTimeout(() => {location.reload();}, 500);
                        },
                        fail: function (response) {
                            toastr.error ("Error. ", '¡Inconcebible!');
                        }
                    });

                }

            },
            error: function (jqXhr, textStatus, xhr) { // provide a bit more info about the error to the console
                console.log(jqXhr);
                if (jqXhr.status == 500) {
                    toastr.error(jqXhr.responseJSON.error, '¡Inconcebible!');
                } else {
                    console.log(" STATUS: " + xhr + " " + textStatus);
                }

            }
        });//end ajax
        $("#btn-worker-establishment-submit").removeAttr("disabled");
        $('#get-worker-establishment').modal('hide');
    });
</script>