apps/buys/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.buys.views import *
from apps.buys.views_PDF import kardex_glp_pdf, print_requirement

urlpatterns = [
    path('', login_required(Home.as_view()), name='home'),
    path('purchase_form/', purchase_form, name='purchase_form'),
    path('save_purchase/', save_purchase, name='save_purchase'),

    #COMPRAS NORMALES
    path('get_purchase_list/', get_purchase_list, name='get_purchase_list'),
    path('get_purchase_annular_list/', get_purchase_annular_list, name='get_purchase_annular_list'),
    path('get_purchase_store_list/', get_purchase_store_list, name='get_purchase_store_list'),
    path('get_detail_purchase_store/', get_detail_purchase_store, name='get_detail_purchase_store'),
    path('get_details_by_purchase/', get_details_by_purchase, name='get_details_by_purchase'),

    path('get_requirement_programming/', get_requirement_programming, name='get_requirement_programming'),
    path('get_programming_invoice/', get_programming_invoice, name='get_programming_invoice'),
    path('save_detail_purchase_store/', save_detail_purchase_store, name='save_detail_purchase_store'),
    path('get_units_by_product/', get_units_by_product, name='get_units_by_product'),
    path('get_scop_truck/', get_scop_truck, name='get_scop_truck'),
    path('save_programming_invoice/', save_programming_invoice, name='save_programming_invoice'),
    path('save_detail_requirement_store/', save_detail_requirement_store, name='save_detail_requirement_store'),
    path('get_expense_programming/', get_expense_programming, name='get_expense_programming'),
    path('save_programming_fuel/', save_programming_fuel, name='save_programming_fuel'),
    path('get_approve_detail_requirement/', get_approve_detail_requirement, name='get_approve_detail_requirement'),
    path('update_details_requirement_store/', update_details_requirement_store, name='update_details_requirement_store'),
    path('update_state_annular_purchase/', update_state_annular_purchase, name='update_state_annular_purchase'),
    path('get_products_by_requirement/', get_products_by_requirement, name='get_products_by_requirement'),
    path('get_list_requirement_stock/', get_list_requirement_stock, name='get_list_requirement_stock'),
    path('get_requirement_balance/', get_requirement_balance, name='get_requirement_balance'),
    path('get_programming_by_truck_and_dates/', get_programming_by_truck_and_dates, name='get_programming_by_truck_and_dates'),
    path('get_report_kardex_glp/', get_report_kardex_glp, name='get_report_kardex_glp'),
    path('get_rateroutes_programming/', get_rateroutes_programming, name='get_rateroutes_programming'),
    # path('SalesList/<int:pk>/', SalesList, name='SalesList'),
    path('kardex_glp_pdf/<str:date_initial>/<str:date_final>/', kardex_glp_pdf, name='kardex_glp_pdf'),
    # path('kardex_glp_pdf/', kardex_glp_pdf, name='kardex_glp_pdf'),
    #requerimientos GLP
    path('requirement_buy_create/', requirement_buy_create, name='requirement_buy_create'),
    path('create_requirement_view/', login_required(create_requirement_view), name='create_requirement_view'),
    path('save_requirement/', login_required(save_requirement), name='save_requirement'),
    path('requirement_buy_save/', requirement_buy_save, name='requirement_buy_save'),
    path('requirement_buy_list/', login_required(get_requeriments_buys_list), name='requirement_buy_list'),
    path('get_requirements_buys_list_approved/', get_requirements_buys_list_approved, name='get_requirements_buys_list_approved'),
    path('save_programming_buys/', save_programming_buys, name='save_programming_buys'),
    path('get_units_product/', get_units_product, name='get_units_product'),

    # ReportLab
    path('print_requirement/<int:pk>/', print_requirement, name='print_requirement'),

    # Payment_Approved
    path('get_modal_payment_buys_approved/', get_modal_payment_buys_approved, name='get_modal_payment_buys_approved'),
    path('new_loan_payment_buys_approved/', new_loan_payment_buys_approved, name='new_loan_payment_buys_approved'),
    path('get_programming_pay/', get_programming_pay, name='get_programming_pay'),
    path('new_payment_programming_glp/', new_payment_programming_glp, name='new_payment_programming_glp'),
    path('get_programming_payment_table/', get_programming_payment_table, name='get_programming_payment_table'),

    # Report programmings all
    path('get_programmings_by_dates/', get_programmings_by_dates, name='get_programmings_by_dates'),
    # Report Graphic
    path('get_report_graphic_glp/', get_report_graphic_glp, name='get_report_graphic_glp'),

    # Report Buys
    path('report_purchases_all/', report_purchases_all, name='report_purchases_all'),
    path('report_purchases_by_supplier/', report_purchases_by_supplier, name='report_purchases_by_supplier'),
    path('get_purchases_by_license_plate/', get_purchases_by_license_plate, name='get_purchases_by_license_plate'),
    path('get_purchases_by_provider_category/', get_purchases_by_provider_category, name='get_purchases_by_provider_category'),
]

dglp/urls.py
# import autocomplete_light
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

from apps.hrm.views import Home
from apps.users.views import Login, logoutUser

# autocomplete_light.autodiscover()
# admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dishes/', include(('apps.dishes.urls', 'dishes'))),
    path('api/v1/', include(('apps.apidishes.urls', 'apidishes'))),
    path('vetstore/', include(('apps.vetstore.urls', 'vetstore'))),
    path('hrm/', include(('apps.hrm.urls', 'hrm'))),
    path('comercial/', include(('apps.comercial.urls', 'comercial'))),
    path('sales/', include(('apps.sales.urls', 'sales'))),
    path('buys/', include(('apps.buys.urls', 'buys'))),
    path('accounting/', include(('apps.accounting.urls', 'accounting'))),

    path('', login_required(Home.as_view()), name='dashboard'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(logoutUser), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += [
#         static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
#         static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     ]

apps/buys/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

from apps.hrm.models import Subsidiary, District, DocumentType
from apps.sales.models import Unit, Product, Supplier, SubsidiaryStore, LoanPayment
from apps.comercial.models import Truck
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust


class Purchase(models.Model):
    STATUS_CHOICES = (('S', 'SIN ALMACEN'), ('A', 'EN ALMACEN'), ('N', 'ANULADO'),)
    TYPE_CHOICES = (('T', 'TICKET'), ('B', 'BOLETA'), ('F', 'FACTURA'),)
    id = models.AutoField(primary_key=True)
    supplier = models.ForeignKey(Supplier, verbose_name='Proveedor', on_delete=models.CASCADE, null=True, blank=True)
    purchase_date = models.DateField('Fecha compra', null=True, blank=True)
    bill_number = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='S')
    truck = models.ForeignKey(Truck, on_delete=models.SET_NULL, null=True, blank=True)
    type_bill = models.CharField('Tipo de comprobante', max_length=1, choices=TYPE_CHOICES, default='T')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Compra'
        verbose_name_plural = 'Compras'

    def total(self):
        response = 0
        purchase_detail_set = PurchaseDetail.objects.filter(purchase__id=self.id)
        for pd in purchase_detail_set:
            response = response + (pd.quantity * pd.price_unit)
        return response


class PurchaseDetail(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE, null=True, blank=True)
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.DecimalField('Cantidad comprada', max_digits=10, decimal_places=2, default=0)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True, blank=True)
    price_unit = models.DecimalField('Precio unitario', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

    def multiplicate(self):
        return self.quantity * self.price_unit

    class Meta:
        verbose_name = 'Detalle compra'
        verbose_name_plural = 'Detalles de compra'


class Requirement_buys(models.Model):
    STATUS_CHOICES = (('1', 'PENDIENTE'), ('2', 'APROBADO'), ('3', 'ANULADO'), ('4', 'FINALIZADO'),)
    STATUS_CHOICES_PAYMENT = (('1', 'PENDIENTE'), ('2', 'PAGADO'), ('3', 'ANULADO'),)
    TYPE_CHOICES = (('M', 'MERCADERIA'), ('I', 'INSUMO'),)
    id = models.AutoField(primary_key=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='1', )
    status_pay = models.CharField('Estado de Pago', max_length=1, choices=STATUS_CHOICES_PAYMENT, default='1', )
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES, default='M', )
    creation_date = models.DateField('Fecha de solicitud', null=True, blank=True)
    number_scop = models.CharField('Numero de scop', max_length=45, null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True)
    approval_date = models.DateField('Fecha de aprobación', null=True, blank=True)
    invoice = models.CharField('Factura', max_length=45, null=True, blank=True)

    def __str__(self):
        return str(self.id)

    def sum_loan_payment_pen(self):
        response = 0
        loan_payment_set = LoanPayment.objects.filter(requirement_detail_buys__requirement_buys=self.id)
        if loan_payment_set.exists():
            for lp in loan_payment_set:
                if lp.get_cash_flow().cash.currency_type == 'S':
                    response = response + lp.price
        return response

    def sum_loan_payment_dollar(self):
        response = 0
        loan_payment_set = LoanPayment.objects.filter(requirement_detail_buys__requirement_buys=self.id)
        if loan_payment_set.exists():
            for lp in loan_payment_set:
                if lp.get_cash_flow().cash.currency_type == 'D':
                    response = response + lp.price
        return response

    def debt(self):
        debt = 0
        price_total = 0
        debt_total = RequirementDetail_buys.objects.filter(requirement_buys=self.id).values('amount')
        for p in debt_total:
            price_total = price_total + p['amount']
        debt = self.sum_loan_payment_dollar() - price_total
        return debt

    class Meta:
        verbose_name = 'Requerimiento'
        verbose_name_plural = 'Requerimientos'


class RequirementDetail_buys(models.Model):
    COIN_CHOICES = ((1, 'DOLAR(ES)'), (2, 'SOLE(S)'),)
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, blank=True)
    requirement_buys = models.ForeignKey('Requirement_buys', on_delete=models.CASCADE, related_name='requirements_buys',
                                         null=True, blank=True)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    amount = models.DecimalField('Importe', max_digits=30, decimal_places=15, default=0)
    price_pen = models.DecimalField('Precio soles', max_digits=30, decimal_places=15, default=0)
    amount_pen = models.DecimalField('Importe soles', max_digits=30, decimal_places=15, default=0)
    coin = models.IntegerField('Moneda', choices=COIN_CHOICES, default=1, )
    change_coin = models.DecimalField('Cambio', max_digits=30, decimal_places=15, default=0)

    def __str__(self):
        return str(self.id)

    def multiplicate(self):
        return self.quantity * self.price

    class Meta:
        verbose_name = 'Detalle requerimiento'
        verbose_name_plural = 'Detalles de requerimiento'


class RequirementBuysProgramming(models.Model):
    STATUS_CHOICES = (('P', 'PROGRAMADO'), ('F', 'FINALIZADO'),)
    id = models.AutoField(primary_key=True)
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE, related_name='truck', null=True, blank=True)
    date_programming = models.DateField('Fecha de solicitud', null=True, blank=True)
    number_scop = models.CharField('Numero de scop', max_length=45, null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='P', )
    subsidiary = models.ForeignKey(Subsidiary, on_delete=models.SET_NULL, null=True, blank=True,
                                   related_name='rpsubsidiary')

    def __str__(self):
        return str(self.id)

    def calculate_total_programming_expenses_price(self):
        # try:
        response = ProgrammingExpense.objects.filter(
            requirementBuysProgramming__id=self.id).values(
            'requirementBuysProgramming').annotate(totals=Sum('price'))
        if (response.exists()):
            return response[0].get('totals')
        else:
            return 0

    # except ProgrammingExpense.DoesNotExist:
    #     return 0

    class Meta:
        verbose_name = 'Programacion de Requerimiento GLP'
        verbose_name_plural = 'Programaciones de Requerimiento GLP'


class Programminginvoice(models.Model):
    STATUS_CHOICES = (('P', 'PENDIENTE'), ('R', 'REGISTRADO'),)
    id = models.AutoField(primary_key=True)
    requirementBuysProgramming = models.ForeignKey(RequirementBuysProgramming, on_delete=models.SET_NULL, null=True,
                                                   blank=True)
    requirement_buys = models.ForeignKey(Requirement_buys, on_delete=models.SET_NULL, null=True, blank=True)
    date_arrive = models.DateField('Fecha de entrada', null=True, blank=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='P', )
    guide = models.CharField('Numero Guia', max_length=45, null=True, blank=True)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField('Precio', max_digits=30, decimal_places=15, default=0)
    subsidiary_store_destiny = models.ForeignKey(SubsidiaryStore, on_delete=models.SET_NULL, null=True, blank=True,
                                                 related_name='destinies')
    subsidiary_store_origin = models.ForeignKey(SubsidiaryStore, on_delete=models.SET_NULL, null=True, blank=True,
                                                related_name='origins')

    def __str__(self):
        return str(self.id)

    def calculate_total_quantity(self):
        response = Programminginvoice.objects.filter(requirement_buys_id=self.requirement_buys.id).values(
            'requirement_buys').annotate(totals=Sum('quantity'))
        # return response.count
        if response:
            return response[0].get('totals')
        else:
            return 0

    def calculate_total_programming_quantity(self):
        response = Programminginvoice.objects.filter(
            requirementBuysProgramming_id=self.requirementBuysProgramming.id).values(
            'requirementBuysProgramming').annotate(totals=Sum('quantity'))
        # return response.count
        if response:
            return response[0].get('totals')
        else:
            return 0

    class Meta:
        verbose_name = 'Factura GLP'
        verbose_name_plural = 'Facturas GLP'


class ProgrammingExpense(models.Model):
    STATUS_CHOICES = (('P', 'PENDIENTE'), ('R', 'REGISTRADO'),)
    TYPE_CHOICES = (

templates/buys/approve_requirement.html
{% if requirement %}
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background: #2b579a">
                <h6 class="modal-title text-white">APROBAR REQUERIMIENTO</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <table class="table table-sm">
                        <tr>
                            <td width="15%" class="align-middle" style="font-size: 12px">Numero requerimiento:</td>
                            <td width="20%" class="align-middle">
                                <input type="text" class="form-control form-control-sm" id="id_requirement"
                                       readonly value="{{ requirement.id }}">
                            </td>
                            <td width="15%" class="align-middle" style="font-size: 12px">Numero Scop:</td>
                            <td width="15%" class="align-middle">
                                <input type="text" readonly class="form-control form-control-sm" id="id_nscop"
                                       readonly value="{{ requirement.number_scop }}">
                            </td>
                            <td width=35%" class="align-middle text-center p-3" rowspan="2">
                                <button type="button" id="id-btn-approve"
                                        class="btn btn-sm btn-success btn-block pb-2 pt-2">Aprobar requerimiento
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td class="align-middle" style="font-size: 12px">Numero comprobante:</td>
                            <td class="align-middle"><input type="text" class="form-control form-control-sm"
                                                            id="id_invoice" required>
                            </td>
                            <td class="align-middle" style="font-size: 12px">
                                Fecha aprobacion:
                            </td>
                            <td class="align-middle">
                                <input type="date" class="form-control form-control-sm" id="id_date_approve"
                                       value="{{ date_now }}">
                            </td>
                        </tr>
                    </table>

                    <table id="tbl-detail-requirements"
                           class="table table-striped align-content-center table-bordered small m-0">
                        <thead>
                        <tr class="text-white text-center" style="background: #2b579a; font-size: 13px;">
                            <th width="2%" class="font-weight-normal">N°</th>
                            <th width="7%" class="font-weight-normal">Producto</th>
                            <th width="12%" class="font-weight-normal">Cantidad</th>
                            <th width="8%" class="font-weight-normal">Unidad</th>
                            <th width="20%" class="font-weight-normal">Precio</th>
                            <th width="20%" class="font-weight-normal">Importe</th>
                            <th width="18%" class="font-weight-normal">Moneda</th>
                            <th width="13%" class="font-weight-normal">Cambio(S/.)</th>
                        </tr>
                        </thead>
                        <tbody id="tbody-details" style="font-size: 13px;">
                        {% for d in requirement.requirements_buys.all %}
                            <tr product="{{ d.product.id }}" class="text-center align-middle font-weight-bold p-0 m-0">
                                <td class="item-detail align-middle">{{ d.id }}</td>
                                <td class="item-name align-middle">{{ d.product.name }}</td>
                                <td class="item-quantity align-middle">{{ d.quantity|floatformat:2 }}</td>
                                <td class="item-unit align-middle" pu="{{ d.unit.id }}">{{ d.unit.name }}</td>
                                <td class="item-price align-middle">{{ d.price|floatformat:10 }}</td>
                                <td class="item-amount align-middle"><input type="number" class="form-control form-control-sm font-weight-bold total"
                                           value="{{ d.multiplicate|floatformat:10 }}"></td>
                                <td class="item-coin align-middle">
                                    <select id="id_coin_glp" name="coin_glp"
                                            class="form-control form-control-sm select-coin">
                                        {% for item in coin_type %}
                                            <option value="{{ item.0 }}">{{ item.1 }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td class="item-change align-middle">
                                    <input type="number" class="form-control form-control-sm font-weight-bold input-change"
                                           value="{{ d.change_coin|floatformat:4 }}">
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div><!-- modal-body -->
                <div class="modal-footer"> &nbsp;
                    {#                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>                &nbsp;#}
                    {#                <button id="save-changes" type="button" class="btn btn-primary">Guardar</button>#}
                </div>
            </form>
        </div>
    </div>
{% else %}
    <h1>No existen compras de requerimientos GLP</h1>
{% endif %}


<script type="text/javascript">
    $('#tbody-details tr td.item-quantity').each(function () {
        let _str = $(this).text();
        _str = _str.replace(',', '.');
        $(this).text(_str);
    });

    $('#tbody-details tr td.item-price').each(function () {
        let _str = $(this).text();
        _str = _str.replace(',', '.');
        $(this).text(_str);
    });

    $('#tbody-details tr td input.total').keyup(function () {
        let _total = parseFloat($(this).val());
        if (_total != '') {
            let _item_quantity = parseFloat($(this).parent('td').parent('tr').find('td.item-quantity').text());
            let _item_price = _total / _item_quantity;
            if (isNaN(_item_price)) {
                $(this).parent('td').parent('tr').find('td.item-price').text((0).toFixed(10));
            } else {
                $(this).parent('td').parent('tr').find('td.item-price').text(_item_price.toFixed(10));
            }
        }
    })

    $('#id-btn-approve').click(function () {

        if (($('#id_invoice').val()).toString() != "" && ($('#id_date_approve').val()).toString() != "") {
            let requirements = {
                "Details": [],
                "pk": $('#id_requirement').val(),
                "invoice": $('#id_invoice').val(),
                "date_approve": $('#id_date_approve').val(),
            };

            $("#tbody-details tr").each(function () {
                if (parseFloat($(this).find("td.item-price").text()) > 0 && (parseInt($(this).find('td.item-coin select.select-coin').val()) > 0 && parseFloat($(this).find('td.item-change input.input-change').val()) > 0)) {
                    let detailObj = {
                        "detail_requirement_id": $(this).find("td.item-detail").text(),
                        "price": $(this).find("td.item-price").text(),
                        "amount": $(this).find("td.item-amount input.total").val(),
                        "coin": $(this).find("td.item-coin select.select-coin").val(),
                        "change_coin": $(this).find("td.item-change input.input-change").val(),
                    };
                    requirements.Details.push(detailObj);
                    $.ajax({

                        url: '/buys/update_details_requirement_store/',
                        async: true,
                        dataType: 'json', // for response
                        type: 'GET',
                        data: {'requirements': JSON.stringify(requirements)},
                        contentType: 'application/json;charset=UTF-8',
                        headers: {"X-CSRFToken": '{{ csrf_token }}'},
                        success: function (response, textStatus, xhr) {
                            if (xhr.status == 200) {
                                toastr.success(response.message, '¡EXITOSO!');
                                setTimeout(() => {
                                    location.reload();
                                }, 500);
                            }
                        },
                        error: function (jqXhr, textStatus, xhr) {
                            $('#add-programing-modal').modal('hide');
                            toastr.error(jqXhr.responseJSON.error, '¡MENSAJE!');
                        }
                    });
                } else {
                    alert("Ingrese el importe por favor!")
                }

            });
        } else {
            alert("Ingrese el comprobante y/o fecha de aprobacion!")
        }
    })

</script>

templates/buys/purchase_annular_list.html
{% extends 'home.html' %}

{% block title %}
coronasoft.dev | Listado de compras anuladas
{% endblock title %}

{% block body %}

<!-- Content -->
<div class="container-fluid">

    <div id="purchase-grid-list" >{% include "buys/purchase_annular_grid_list.html" %}</div>

</div>

<div class="modal fade" id="assignment-annular" tabindex="-1" role="dialog" aria-labelledby="ModalHelpTitle" aria-hidden="true"></div>


{% endblock body %}

{% block extrajs %}

<script type="text/javascript">

    {#$('#puchase-data-grid').dataTable();#}
    $('#purchase-annular-data-grid').DataTable({
        "language": {
          "url": "//cdn.datatables.net/plug-ins/1.10.15/i18n/Spanish.json"
        }
    });

</script>
{% endblock extrajs %}

templates/buys/report_programming_by_truck_and_dates_grid.html
<table class="table  table-striped align-content-center table-bordered response">
    <thead class="text-white" style="background-color: rgb(105,105,105);">
    <tr>
        <th class="text-center" style="width: 5px">Numero</th>
        <th class="text-center" style="width: 20px">Fecha</th>
        <th class="text-center" style="width: 10px">Placa</th>
        <th class="text-center" style="width: 30px">Numero scop</th>
        <th class="text-center" style="width: 20px">Guia</th>
        <th class="text-center" style="width: 30px">Cantidad</th>
        <th class="text-center" style="width: 20px">Detalle gastos</th>
        {#             <th class="text-center">Gastos Subtotal</th>#}
    </tr>
    </thead>
    <tbody>
    {% for p in programmings %}
        <tr>
            <td class="item text-center align-middle"></td>
            <td class="text-center  align-middle">{{ p.programminginvoice_set.first.date_arrive }}</td>
            <td class="text-center  align-middle">{{ p.truck.license_plate }}</td>
            <td class="text-center  align-middle">{{ p.number_scop }}</td>
            <td class="text-center  align-middle">{{ p.programminginvoice_set.first.guide }}
            </td>
            <td class="decimal text-center  align-middle">{{ p.programminginvoice_set.last.calculate_total_programming_quantity|floatformat:2 }}
                {#                 {% for i in p.programminginvoice_set.all %}#}
                {#                    {{ i.quantity }} <br>#}
                {#                 {% endfor %}#}
            </td>
            {#             <td class="text-center">{{ p.programminginvoice_set.first.subsidiary_store.subsidiary.name }}</td>#}
{#            <td class="text-right  align-middle">#}
{#                {% for i in p.programmingexpense_set.all %}#}
{#                    {{ i.get_type_display }} S/. {{ i.price|floatformat:2 }} <br>#}
{#                {% endfor %}#}
{#                <div class="dropdown-divider m-1 border-danger"></div>#}
{#                <strong>Total: S/. {{ p.calculate_total_programming_expenses_price|floatformat:2 }}</strong>#}
{#            </td> #}
             {% if forloop.first %}
                <td class="text-right align-middle text-center" rowspan="{{ programmings.all.count }}" >{{ purchases|safe }}</td>
            {% endif %}
            {#             <td class="text-center  align-middle">#}
            {#                 {{ p.calculate_total_programming_expenses_price|floatformat:2 }}#}
            {#             </td>#}
        </tr>
    {% endfor %}
    <tr class="text-white font-weight-bold" style="background-color: rgb(105,105,105);">
        <td class="text-center" colspan="5"><strong>Numero total de viajes realizados
            = </strong>{{ programmings.all.count }}</td>

        <td colspan="1" class="text-center decimal"><strong>Cantidad transportada
            = </strong>{% if total_quantity %}{{ total_quantity|floatformat:2 }} {% else %} 0.00 {% endif %} </td>
{#        <td colspan="1" class="text-center decimal"><strong>Total gasto = S/. </strong> {% if total_price %}#}
{#            {{ total_price|floatformat:2 }} {% else %} 0.00 {% endif %}</td>#}
        <td colspan="1" class="text-center decimal"><strong>Total gasto = S/ </strong>{{ purchases|safe }}</td>
    </tr>
    </tbody>
</table>

<script>
    $index = 1;
    $('table tr td.item').each(function () {
        $(this).text($index);
        $index++;
    });
    $('table tr td.decimal').each(function () {
        let _str = $(this).text();
        _str = _str.replace(',', '.');
        $(this).text(_str);
    });
</script>

templates/buys/report_programming_grid_all.html
<table class="table  table-striped align-content-center table-bordered response">
    <thead class="text-white" style="background-color: rgb(105,105,105);">
    <tr>
        <th class="text-center">Placa</th>
        <th class="text-center">Numero de Viajes</th>
        <th class="text-center">Cantidad</th>
        <th class="text-center">Gastos</th>

    </tr>
    </thead>
    <tbody>
    {% for key, value in dictionary.items %}
        <tr>
            <td class="text-center  align-middle">{{ value.license_plate }}</td>
            <td class="text-center  align-middle">{{ value.count }}</td>
            <td class="text-center  align-middle">{{ value.quantity_total }}</td>
            <td class="text-center  align-middle">{{ value.expenses }}</td>

        </tr>
    {% endfor %}
    </tbody>
</table>

<script>

</script>